name: Test

on:
  workflow_dispatch:

jobs:
  build-bicep:
    name: 'Build CLI (${{ matrix.rid }})'
    runs-on: ${{ matrix.os }}

    env:
      # don't print dotnet logo
      DOTNET_NOLOGO: true

      # disable telemetry (reduces dotnet tool output in logs)
      DOTNET_CLI_TELEMETRY_OPTOUT: true

    strategy:
      # let us get failures from other jobs even if one fails
      fail-fast: false

      matrix:
        include:
        - os: 'windows-latest'
          rid: 'win-x64'
          configuration: 'release'
          publishLanguageServer: 'false'
          publishPackages: 'false'
        - os: 'ubuntu-latest'
          rid: 'linux-x64'
          configuration: 'release'
          publishLanguageServer: 'true'
          publishPackages: 'true'
        - os: 'ubuntu-latest'
          rid: 'linux-musl-x64'
          configuration: 'release'
          publishLanguageServer: 'false'
          publishPackages: 'false'
        - os: 'macos-latest'
          rid: 'osx-x64'
          configuration: 'release'
          publishLanguageServer: 'false'
          publishPackages: 'false'

    steps:
      - uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0 # avoid shallow clone so nbgv can do its work.
          submodules: true

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1.8.1
      
      - name: Build
        run: dotnet build --configuration ${{ matrix.configuration }}

      - name: Test
        run: dotnet test --configuration ${{ matrix.configuration }} --logger trx --blame --collect:"XPlat Code Coverage" --settings ./.github/workflows/codecov.runsettings --results-directory ./TestResults/ --filter ClassName=Bicep.Core.UnitTests.FileSystem.FileLockTests ./src/Bicep.Core.UnitTests/Bicep.Core.UnitTests.csproj

      - name: Upload Test Results
        uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: Bicep.TestResults.${{ matrix.rid }}
          path: ./TestResults/**/*.trx
          if-no-files-found: error